# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Script with Service Account

on:
  push:
    branches:
      - test  # Set to the branch you want to trigger the workflow on
  workflow_dispatch:
    inputs:
      custom_parameter:
        description: 'Custom input parameter'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Set up Service Account Key
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-sa.json

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python csv-xcel-s3.py

